
"""
GOAL:
  define constraints on the data which can be tested!

questions:
  can you test relationships with non-AC tables? yah prolly
"""

pardot_visitoractivity:
  constraints:
    not_null:
      - prospect_id
    unique: []
    relationships:
      - {from: type, to: pardot_visitoractivity_events_meta, field: type_name}
      - {from: type, to: pardot_visitoractivity_types_meta, field: type}

pardot_visitoractivity_events_meta:
  constraints:
    not_null:
      - type_name
      - event_name
    unique:
      - type_name
      - event_name
    relationships:
      - {from: type_name, to: pardot_visitoractivity, field: type}

pardot_visitoractivity_types_meta:
  constraints:
    not_null:
      - type
      - type_decoded
    unique:
      - type
      - type_decoded
    relationships:
      - {from: type, to: pardot_visitoractivity, field: type}
