
pardot_visitoractivity:
  constraints:
    not_null:
      - prospect_id
    unique: []
    relationships:
      - {from: type, to: pardot_visitoractivity_events_meta, field: type}
      - {from: type, to: pardot_visitoractivity_types_meta, field: type}

pardot_visitoractivity_events_meta:
  constraints:
    not_null:
      - type_name
      - event_name
    unique:
      - event_name
    relationships:
      - {from: type, to: pardot_visitoractivity, field: type}

pardot_visitoractivity_types_meta:
  constraints:
    not_null:
      - type
      - type_decoded
    unique:
      - type
      - type_decoded
    relationships:
      - {from: type, to: pardot_visitoractivity, field: type}
